version: "3.8"
services:
  backend:
    build: ./back-end
    container_name: festival-backend
    ports:
      - "3000:3000"
    env_file:
      - ./back-end/.env
    restart: unless-stopped

  frontend:
    container_name: festival-frontend
    build:
      context: ./front-end
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - backend